# Generated by Django 5.2.1 on 2025-06-01 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_studentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='active_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 8, 8, 15, 30, 888778, tzinfo=datetime.timezone.utc), help_text='퀴즈 활성화 종료 시간'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=60, help_text='퀴즈 제한 시간(초)'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='words',
            field=models.ManyToManyField(through='vocabulary.QuizWord', to='vocabulary.word'),
        ),
    ]
