# Generated by Django 5.2.1 on 2025-06-01 08:28

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0004_quiz_active_until_quiz_time_limit_quiz_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='active_from',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='퀴즈 활성화 시작 시간'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='active_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 8, 8, 28, 11, 844465, tzinfo=datetime.timezone.utc), help_text='퀴즈 활성화 종료 시간'),
        ),
    ]
