# Generated by Django 5.2.1 on 2025-06-01 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0005_quiz_active_from_alter_quiz_active_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='active_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 8, 19, 32, 14, 78111, tzinfo=datetime.timezone.utc), help_text='퀴즈 활성화 종료 시간'),
        ),
    ]
